server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: localhost

mybatis:
  type-aliases-package: com.leyou.order.pojo

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null # 默认不返回null的数据

ly:
  jwt:
    pubKeyPath: D:\heima\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
    cookieMaxAge: 1800
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
    appID: wx8397f8696b538317
    mchID: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    httpConnectionTimeoutMs: 1000
    httpReadTimeoutMs: 5000
    notifyUrl: http://4en7ay.natappfree.cc/notify/pay

