server:
  port: 8086

spring:
  application:
    name: sms-service

  # 配置RabbitMQ
  rabbitmq:
    username: leyou
    password: leyou
    virtual-host: /leyou
    host: 192.168.1.128

  # 配置redis
  redis:
    host: 192.168.1.128
ly:
  sms:
    apikey:  ac1275fe3f5b94a506e15449a0b0fcb0 # 梦网短信网关的apiKey
    userId: E107UB # 梦网短信网关的userId
    pwd: j5vKdV # 梦网短信网关的password
    ipAddress1: api01.monyun.cn:7901


