server:
  port: 8088
spring:
  application:
    name: cart-service

  # 配置redis
  redis:
    host: 192.168.1.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ly:
  jwt:
    pubKeyPath: D:\heima\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN